// <auto-generated />
using ExemploClientServer.Infraestrutura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExemploClientServer.Infraestrutura.Migrations
{
    [DbContext(typeof(ExemploClientServerContext))]
    [Migration("20180828162041_ProcessEntity")]
    partial class ProcessEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ExemploClientServer.Core.Models.Computer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Inativo");

                    b.Property<string>("Ip");

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Computers");
                });

            modelBuilder.Entity("ExemploClientServer.Core.Models.Process", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ComputerId");

                    b.Property<bool>("Inativo");

                    b.Property<string>("Nome");

                    b.Property<int>("ProcessId");

                    b.HasKey("Id");

                    b.HasIndex("ComputerId");

                    b.ToTable("Process");
                });

            modelBuilder.Entity("ExemploClientServer.Core.Models.Process", b =>
                {
                    b.HasOne("ExemploClientServer.Core.Models.Computer", "Computer")
                        .WithMany("Process")
                        .HasForeignKey("ComputerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
